#!/bin/bash


usage() {
	echo "Backup a file"
	echo "USAGE: backup originalFile"
	echo "OUTPUT: originalFile.YYYYMMDD.mmmm~"
}

backup() {
	# timestamp
	# timeStamp=$(date +%Y%m%d);
	timeStamp=$(source get_timestamp)
	backupFile="$1.$timeStamp~";
	i=0;

	while [ -f "$backupFile" ]; do
		i=$(($i + 1));
		backupFile="$1.$timeStamp-$i~";
	done

	echo "File to backup: $1" ;
	echo "Backup location: $backupFile";

	cp "$1" "$backupFile";

	if [ $? == 0 ]; then
		echo "Backup successful";
		exit 0
	fi

	echo "Backup failed";
	exit 1
}

if [ $# -eq 0 ];then
	usage
fi

if [ ! -f "$1" ]; then
	echo "File not found"
	exit 1
fi

backup "$1"

